"""
setup_wizard.py  —  Jarvis First-Run Setup
==========================================
Runs automatically the first time Jarvis starts (when .env is missing or empty).
Opens a clean GUI window that collects all required API keys and settings,
then writes a proper .env file and shows a confirmation before launching.

Usage (called automatically from main.py — see integration note at the bottom):
    from setup_wizard import run_if_needed
    run_if_needed()          # Must be called BEFORE any config / api imports
"""

import os
import json
import sys
import tkinter as tk
import tkinter.messagebox as messagebox

# Try to use customtkinter (same lib the rest of Jarvis uses); fall back to plain tk
try:
    import customtkinter as ctk
    USE_CTK = True
except ImportError:
    USE_CTK = False


# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

FIELDS = [
    {
        "key": "GROQ_API_KEY",
        "label": "Groq API Key  *",
        "hint": "Get it free at console.groq.com",
        "required": True,
        "secret": True,
    },
    {
        "key": "OPENROUTER_API_KEY",
        "label": "OpenRouter API Key  *",
        "hint": "Get it at openrouter.ai/keys",
        "required": True,
        "secret": True,
    },
    {
        "key": "USER_NAME",
        "label": "Your Name  *",
        "hint": 'What Jarvis calls you (e.g. "Liam")',
        "required": True,
        "secret": False,
    },
    {
        "key": "EMAIL_ADDRESS",
        "label": "Gmail Address",
        "hint": "Used for send/read email skill (optional)",
        "required": False,
        "secret": False,
    },
    {
        "key": "EMAIL_APP_PASSWORD",
        "label": "Gmail App Password",
        "hint": "Google Account → Security → App Passwords (optional)",
        "required": False,
        "secret": True,
    },
    {
        "key": "PORCUPINE_KEY",
        "label": "Porcupine Wake-Word Key",
        "hint": "Free at console.picovoice.ai — skip for Whisper-based detection",
        "required": False,
        "secret": True,
    },
    {
        "key": "CONTACTS_JSON",
        "label": "Contacts (JSON)",
        "hint": '{"Mom": "+1234567890", "Dad": "+0987654321"}  — leave blank if unused',
        "required": False,
        "secret": False,
    },
]


def _env_is_configured() -> bool:
    """Return True if .env already exists and has at least the two required keys filled in."""
    if not os.path.exists(ENV_PATH):
        return False
    values = {}
    with open(ENV_PATH, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                values[k.strip()] = v.strip()
    required_keys = [f["key"] for f in FIELDS if f["required"]]
    return all(values.get(k, "") not in ("", "your_groq_key_here", "your_openrouter_key_here")
               for k in required_keys)


def _write_env(values: dict):
    lines = [
        "# ── Jarvis .env ── auto-generated by setup_wizard.py ──",
        "# Do NOT share or commit this file. It is in .gitignore.",
        "",
    ]
    for field in FIELDS:
        key = field["key"]
        val = values.get(key, "").strip()
        lines.append(f"{key}={val}")
    lines.append("")
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ──────────────────────────────────────────────
# GUI
# ──────────────────────────────────────────────

# Colour palette — matches Jarvis dark theme
BG       = "#0d0d0d"
PANEL    = "#141414"
ACCENT   = "#00aaff"
ACCENT2  = "#0066cc"
TEXT     = "#e8e8e8"
MUTED    = "#666666"
ERROR    = "#ff4444"
SUCCESS  = "#00cc66"
BORDER   = "#1e1e1e"
INPUT_BG = "#1a1a1a"


class SetupWizard:
    def __init__(self):
        if USE_CTK:
            ctk.set_appearance_mode("dark")
            ctk.set_default_color_theme("blue")
            self.root = ctk.CTk()
        else:
            self.root = tk.Tk()

        self.root.title("Jarvis — First-Time Setup")
        self.root.geometry("680x780")
        self.root.resizable(False, False)
        self.root.configure(bg=BG)

        # Centre on screen
        self.root.update_idletasks()
        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        x = (sw - 680) // 2
        y = (sh - 780) // 2
        self.root.geometry(f"680x780+{x}+{y}")

        self.entries: dict[str, tk.StringVar] = {}
        self.completed = False

        self._build_ui()
        self.root.protocol("WM_DELETE_WINDOW", self._on_close)

    # ── Build UI ────────────────────────────────

    def _build_ui(self):
        # ── Header ──────────────────────────────
        header = tk.Frame(self.root, bg=BG, pady=24)
        header.pack(fill="x", padx=32)

        tk.Label(
            header, text="⚡  JARVIS SETUP", font=("Segoe UI", 22, "bold"),
            bg=BG, fg=ACCENT
        ).pack(anchor="w")
        tk.Label(
            header,
            text="Enter your API keys below. They are saved locally in a .env file\n"
                 "and are NEVER uploaded or shared.",
            font=("Segoe UI", 10), bg=BG, fg=MUTED, justify="left"
        ).pack(anchor="w", pady=(4, 0))

        # thin separator
        tk.Frame(self.root, bg=ACCENT, height=1).pack(fill="x", padx=32)

        # ── Scrollable form area ─────────────────
        canvas_frame = tk.Frame(self.root, bg=BG)
        canvas_frame.pack(fill="both", expand=True, padx=0, pady=0)

        canvas = tk.Canvas(canvas_frame, bg=BG, highlightthickness=0)
        scrollbar = tk.Scrollbar(canvas_frame, orient="vertical", command=canvas.yview)
        self.form_frame = tk.Frame(canvas, bg=BG)

        self.form_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        canvas.create_window((0, 0), window=self.form_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        scrollbar.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)

        # bind mouse wheel
        canvas.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(-1*(e.delta//120), "units"))

        for field in FIELDS:
            self._add_field(self.form_frame, field)

        # ── Bottom bar ──────────────────────────
        bottom = tk.Frame(self.root, bg=PANEL, pady=16)
        bottom.pack(fill="x", side="bottom")

        tk.Frame(bottom, bg=BORDER, height=1).pack(fill="x")

        btn_frame = tk.Frame(bottom, bg=PANEL)
        btn_frame.pack(pady=(12, 0))

        # Save & Launch button
        self.save_btn = tk.Button(
            btn_frame,
            text="  Save & Launch Jarvis  ",
            font=("Segoe UI", 12, "bold"),
            bg=ACCENT, fg="white", activebackground=ACCENT2,
            relief="flat", cursor="hand2", padx=20, pady=10,
            command=self._on_save
        )
        self.save_btn.pack(side="left", padx=8)

        # Status label
        self.status_var = tk.StringVar(value="")
        self.status_label = tk.Label(
            btn_frame, textvariable=self.status_var,
            font=("Segoe UI", 10), bg=PANEL, fg=ERROR
        )
        self.status_label.pack(side="left", padx=8)

    def _add_field(self, parent, field: dict):
        """Add a labelled input row for one env variable."""
        wrapper = tk.Frame(parent, bg=BG, pady=6)
        wrapper.pack(fill="x", padx=32)

        # Label row
        label_row = tk.Frame(wrapper, bg=BG)
        label_row.pack(fill="x")

        required_star = "  *required" if field["required"] else "  optional"
        star_color = ACCENT if field["required"] else MUTED

        tk.Label(
            label_row, text=field["label"],
            font=("Segoe UI", 11, "bold"), bg=BG, fg=TEXT
        ).pack(side="left")
        tk.Label(
            label_row, text=required_star,
            font=("Segoe UI", 9), bg=BG, fg=star_color
        ).pack(side="left", padx=(6, 0))

        # Hint
        tk.Label(
            wrapper, text=field["hint"],
            font=("Segoe UI", 9), bg=BG, fg=MUTED, justify="left"
        ).pack(anchor="w", pady=(1, 3))

        # Entry frame with border effect
        entry_frame = tk.Frame(wrapper, bg=ACCENT, padx=1, pady=1)
        entry_frame.pack(fill="x")

        var = tk.StringVar()
        show_char = "•" if field["secret"] else ""

        entry = tk.Entry(
            entry_frame, textvariable=var,
            font=("Consolas", 11), bg=INPUT_BG, fg=TEXT,
            insertbackground=ACCENT, relief="flat",
            show=show_char, bd=0
        )
        entry.pack(fill="x", ipady=8, ipadx=10)

        # Toggle show/hide for secret fields
        if field["secret"]:
            self._add_toggle(wrapper, entry, show_char)

        self.entries[field["key"]] = var

        # Spacer line
        tk.Frame(wrapper, bg=BORDER, height=1).pack(fill="x", pady=(6, 0))

    def _add_toggle(self, parent, entry_widget, original_show):
        def toggle():
            current = entry_widget.cget("show")
            entry_widget.config(show="" if current == "•" else "•")
            btn.config(text="Hide" if current == "•" else "Show")

        btn = tk.Button(
            parent, text="Show",
            font=("Segoe UI", 8), bg=PANEL, fg=MUTED,
            relief="flat", cursor="hand2", bd=0,
            command=toggle
        )
        btn.pack(anchor="e", pady=(2, 0))

    # ── Actions ─────────────────────────────────

    def _on_save(self):
        # Validate required fields
        missing = []
        for field in FIELDS:
            if field["required"]:
                val = self.entries[field["key"]].get().strip()
                if not val:
                    missing.append(field["label"].replace("  *", ""))

        if missing:
            self.status_var.set(f"Missing: {', '.join(missing)}")
            self.status_label.config(fg=ERROR)
            return

        # Validate CONTACTS_JSON if provided
        contacts_raw = self.entries["CONTACTS_JSON"].get().strip()
        if contacts_raw:
            try:
                json.loads(contacts_raw)
            except json.JSONDecodeError:
                self.status_var.set("Contacts JSON is not valid. Check the format.")
                self.status_label.config(fg=ERROR)
                return

        # Collect values and write .env
        values = {key: var.get().strip() for key, var in self.entries.items()}
        _write_env(values)

        self.status_var.set("✓  Saved!")
        self.status_label.config(fg=SUCCESS)
        self.save_btn.config(state="disabled")
        self.completed = True

        self.root.after(900, self.root.destroy)

    def _on_close(self):
        if not self.completed:
            if messagebox.askyesno(
                "Exit Setup",
                "Jarvis can't start without API keys.\n\nExit anyway?"
            ):
                sys.exit(0)
        else:
            self.root.destroy()

    # ── Run ────────────────────────────────────

    def run(self):
        self.root.mainloop()
        return self.completed


# ──────────────────────────────────────────────
# Public entry point — call this from main.py
# ──────────────────────────────────────────────

def run_if_needed():
    """
    Call this at the very top of main.py, before any other Jarvis imports.
    If .env is already filled in, this returns immediately (zero overhead).
    If .env is missing or incomplete, opens the setup wizard and blocks until done.
    """
    if _env_is_configured():
        return  # Already set up — nothing to do

    print("[SETUP] .env not found or incomplete — launching setup wizard...")
    wizard = SetupWizard()
    success = wizard.run()

    if not success:
        print("[SETUP] Setup cancelled. Exiting.")
        sys.exit(0)

    print("[SETUP] Configuration saved to .env — starting Jarvis.")


# ──────────────────────────────────────────────
# Allow running standalone for testing:  python setup_wizard.py
# ──────────────────────────────────────────────
if __name__ == "__main__":
    # Force-show the wizard even if .env exists (useful during dev)
    wizard = SetupWizard()
    wizard.run()